name: Prettier check

on:
 push:
  branches: [master]
 pull_request:
  branches: [master]

jobs:
 format:
  name: ✨ Prettier
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v1
   - run: npm i prettier
   - run: npm run format:check